# Generated by Django 5.1 on 2025-04-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_place_address_alter_place_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='social_links',
        ),
        migrations.AddField(
            model_name='place',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='place',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='place',
            name='tiktok',
            field=models.URLField(blank=True, null=True, verbose_name='TikTok'),
        ),
        migrations.AddField(
            model_name='place',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='place',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube'),
        ),
    ]
