# Generated by Django 5.1 on 2025-04-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_birthdate'),
        ('places', '0005_remove_place_social_links_place_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_places',
            field=models.ManyToManyField(blank=True, to='places.place'),
        ),
    ]
